// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktqfrogfartulsrvfytw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cWZyb2dmYXJ0dWxzcnZmeXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNDU0NjYsImV4cCI6MjA1MzgyMTQ2Nn0.sKQdVfvK9XgsWORk22eLr18ZXx14q5xUEFUL_yGP5Xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);